service: nestjs-serverless

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: dist/main.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true